

CREATE TABLE GRUPOTAREAS(
    NOMBRE_GRUPO VARCHAR(100) PRIMARY KEY,
    DESCRIPCION VARCHAR(100)
);

CREATE TABLE INTEGRANTE(
    ID_INTEGRANTE INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE_INTEGRANTE VARCHAR(100),
    CORREO_INTEGRANTE VARCHAR(100)
);

CREATE TABLE DETALLE_GRUPOTAREAS(
    NOMBRE_GRUPO VARCHAR(100),
    ID_INTEGRANTE INT,
    FOREIGN KEY (NOMBRE_GRUPO) REFERENCES GRUPOTAREAS(NOMBRE_GRUPO),
    FOREIGN KEY (ID_INTEGRANTE) REFERENCES INTEGRANTE(ID_INTEGRANTE)
);


CREATE TABLE TAREAS( 
    ID_TAREA INT AUTO_INCREMENT PRIMARY KEY,
    NOM_TAREA VARCHAR(100),
    FEC_INI DATE NOT NULL,
    FEC_FIN DATE NOT NULL,
    DESCRIPCION VARCHAR(100),
    ESTADO VARCHAR(3),
    NOMBRE_GRUPO VARCHAR(100),
    ASIGNADO_TAREA INT,
    FOREIGN KEY (NOMBRE_GRUPO) REFERENCES GRUPOTAREAS(NOMBRE_GRUPO),
    FOREIGN KEY (ASIGNADO_TAREA) REFERENCES INTEGRANTE(ID_INTEGRANTE)
);

