CREATE TABLE TAREAS(
    ID_TAREA INT AUTO_INCREMENT PRIMARY KEY,
    NOM_TAREA VARCHAR(100),
    FEC_INI DATE NOT NULL,
    FEC_FIN DATE NOT NULL,
    DESCRIPCION VARCHAR(100),
    ESTADO VARCHAR(3)
);